# Sidebar navigation

- label: 'What is Conflux?'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Documentation
  color: #2c2c2c
  items:
    - label: 'StateProvider'
      link: '/api/stateprovider'
    - label: 'useInitialState Hook'
      link: '/api/useinitialstate'
    - label: 'Reducers'
      link: '/api/reducers'
    - label: 'Context Object'
      link: '/api/context-object'
- label: Testing
  link: '/testing'
- label: About
  link: '/about'
- label: 'GitHub'
  link: 'https://github.com/dustinmyers/react-conflux'
